### ISSUE TITLE
Way to validate subscription info

### ISSUE THREAD

**Issue by YoungKyonYou** [interaso/webpush#27]
Is there a way to validate a subscription info? 
When subscription is not valid it doesn't show exception.
Is there any way?

**Comment by YoungKyonYou** [comment]
solved with using SubscriptionState

**Comment by morki** [comment]
Nice to hear you solved it. Would you suggest any change in documentation to make it more obvious?

**Comment by YoungKyonYou** [comment]
I just starred your library, well to make it obvious I guess making more code snippets and specifying readme.md will be more helping! Thank you
